### ISSUE TITLE
Static page generation for website

### ISSUE THREAD

**Issue by jamesknelson** [jamesknelson/junctions#12]
Website is currently a single-page app, but there really should be HTML pages generated for each of its pages.

In order to do this, the processing on SITE.js files currently handled by the sitepack loader will need to be handled by node itself.

The general idea is:

- Load root SITE.js and build root junction, like in current website
- Walk this junction, creating a list of locations to render
- For each of these locations, create an in-memory history and use it to render the application to a string
- Will also need to take the route's title and add it to the generated page's <title> tag.

**Comment by manjula91** [comment]
Can i take this up?

**Comment by jamesknelson** [comment]
@manjula91 I'd love someone to take this up! Although before you get started, I'd be keen to hear how you want to approach this? Do you already have an understanding of how the site works?

**Comment by manjula91** [comment]
I would want some basics documents to get started with.

Although I have the idea about the topic to have static website.

But it would be good if you share over the document.

I am javascript developer manjuladube.com here's my profile

Manjula

**Comment by manjula91** [comment]
Started on it. Any slack channel where we could discuss ?

Manjula

**Comment by jamesknelson** [comment]
@manjula91 There is no slack channel as of yet. Before you get started, please let me know how you want to approach turning the site into a static site. I don't really have time at the moment to explain how the website works, so I'd like to make sure that we're on the same page before you spend any effort.

**Comment by jamesknelson** [comment]
Website is now statically generated. Closing.
