### ISSUE TITLE
Part of sire fails in Firefox

### ISSUE THREAD

**Issue by aitchnyu** [jamesknelson/junctions#16]
The console throws an error and I am unable to route. The address bar changes but the content remains the same.

I start at 

> https://junctions.js.org/docs/introduction/do-i-need-a-router

and click a link and the address bar changes to 

> https://junctions.js.org/docs/introduction/locations-routes-and-maps

but the content never budges.

I get this stacktrace on the bundled js
```
TypeError: this.refs.html.querySelectorAll(...).forEach is not a function
...
```

This link works perfectly: https://junctions.js.org/examples/Raw

I am using Firefox 47 on an EOLed Ubuntu. I hope I am helpful enough. I wish your project the best!

**Comment by jamesknelson** [comment]
Wow, you're right. I didn't test in Firefox. That is embarrassing. Will fix this ASAP.

**Comment by jamesknelson** [comment]
This should be fixed now.
