### ISSUE TITLE
Auth guidance

### ISSUE THREAD

**Issue by RickDT** [jamesknelson/junctions#19]
Is there a recommend way of handling authorized URLs with Junctions?

**Comment by jamesknelson** [comment]
Could you give me some more details as to what you mean by authorised URLs, and how you'd like to handle them?

**Comment by RickDT** [comment]
Sure. I'm just thinking of URLs that require a login, such as `/inbox`. Is there a built-in way to handle that (like a way to pass a callback function) or is it just a matter of how one implements their Converters, Junctions, Locations, or Routes?

Ideally it would be a great addition to the Guide or Examples page.

**Comment by jamesknelson** [comment]
I agree that it would be nice to have a guide for this.

There is no built in way to handle it, but it is definitely possible. Given the converter just converts a URL into a `Route`, you'll just need to look at the `Route` and decided whether the user is authenticated before rendering any content.

**Comment by RickDT** [comment]
Thanks.
