### ISSUE TITLE
How to keep get parameters?

### ISSUE THREAD

**Issue by rmakarov94** [jamesknelson/junctions#23]
Good day!
I have an url like:
site.com/thing?version=5
where thing is Route
I need get parameter to handle request correctly on server. But it's vanished after router initialisation. How to keep it?

**Comment by jamesknelson** [comment]
I'm not exactly sure what you mean by vanished. Could you give me a concrete example of how you're setting up the router?

**Comment by rmakarov94** [comment]
```
const junction = createJunction({
  designer: {
    default: true
  }
})
```
site.com/designer?version=5
become
site.com/designer

**Comment by jamesknelson** [comment]
In order to get the params, you'll need to specify them as `paramTypes`. For example:

```
const junction = createJunction({
  designer: {
    default: true,
    paramTypes: {
      version: true
    }
  }
})
```

**Comment by rmakarov94** [comment]
It's work. Thank you!
