### ISSUE TITLE
Dynamically pushing to a new route

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jamesknelson/junctions#29]
Is it possible to dynamically switch to a new route? In my case, I'm doing an API request when user clicks a button. If the request was successful, they are routed to a new page.

**Comment by jamesknelson** [comment]
Yep! You'll need to use the `pushLocation` or `replaceLocations` methods of the BrowserNavigation object. For example:

```js
// supports string or `Location` object
navigation.pushLocation('/welcome')
navigation.pushLocation({ pathname: '/welcome' })
```

If you're using the `<JunctionNavigation>` component, you'll find the `navigation` object on the `env` prop that is passed into your component.

Let me know if it works!
