### ISSUE TITLE
Mobile Site

### ISSUE THREAD

**Issue by jamesknelson** [jamesknelson/junctions#6]
The documentation site looks pretty bad on mobile. It would be nice to make the following changes:

- Move the side menu into a drop-down menu above the site content on narrow screens
- Make the example code wrap when viewing on narrow screens

Also, the font sizes could probably use some adjustment.

**Comment by bnlambert** [comment]
How can I proceed with this? Any link to source code?

**Comment by jamesknelson** [comment]
You should be able to get the site running by following the instructions at the bottom of README.md in the root directory. The relevant code is in site/wrappers/MenuWrapper.*

Once you've got it running, the main thing which still needs doing is displaying a dropdown menu for navigation on mobile. If you do have a go at this, please make sure you use raw JavaScript and React, as I don't want to include jQuery or other libraries on the documentation website.

**Comment by jamesknelson** [comment]
Finished this off, closing.
